### ISSUE TITLE
Camera.setRange() function only effective if called after Camera.open()

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-camera#11]
### Python Library versions

```
TauLidarCamera 0.0.2
TauLidarCommon 0.0.2
```

### Camera Info
> If possible, paste the output of `camera.info()` from Python (after camera has been successfully opened)

```
ToF camera opened successfully:
    model:      4.0
    firmware:   3.3
    uid:        450225
    resolution: 160x60
    port:       /dev/cu.usbmodem00000000001A1
```

### Describe the bug

When calling `Camera.setRange()` before `Camera.open()`, the values passed to `setRange()` have no impact on the depth map colouring

### Steps to Reproduce

1. In the [current version of the `distance.py` example program](https://github.com/OnionIoT/tau-lidar-camera/blob/1a7190e6820a55529cf8807f122e31e61415d632/examples/distance.py), **comment out line 19**, and run the program
2. Screenshot the depth map output and kill the program
3. Go back to `distance.py` and change `Camera.setRange(0, 1200)` on line 12 to `Camera.setRange(0, 7500)`
4. Screenshot the depth map output and kill the program

### What is happening?

Following the steps above, you'll see there is no change to the colouring of the depth map

With `Camera.setRange(0, 1200)` on line 12:
![before-open-set-1200](https://user-images.githubusercontent.com/6757320/109882062-465db280-7c47-11eb-8c09-571bd5563782.png)

With `Camera.setRange(0, 7500)` on line 12:
![before-open-set-7500](https://user-images.githubusercontent.com/6757320/109882074-4bbafd00-7c47-11eb-9cc9-ee7005a5dc52.png)

### What is expected?

Expecting to see the depth map colouring change when different values are passed to `Camera.setRange(0, 7500)`

If the program is changed to call `Camera.setRange()` **AFTER** `Camera.open()`, only then does the colouring change:

With `Camera.setRange(0, 1200)` on line **19**:
![after-open-set-1200](https://user-images.githubusercontent.com/6757320/109882203-83c24000-7c47-11eb-9314-629cc4d7811c.png)

With `Camera.setRange(0, 7500)` on line **19**:
![after-open-set-7500](https://user-images.githubusercontent.com/6757320/109882210-86bd3080-7c47-11eb-9c89-2da086d23226.png)

**Comment by greenbreakfast** [comment]
@vsemi can you comment on this bug? Should we just always call `Camera.setRange()` AFTER `Camera.open()`?

**Comment by vsemi** [comment]
The reason is the open() method called setDefaultParameters() and it reset any parameters set before open(). Doing this is to prevent crash if no parameters been set and user doing other operation other than set necessary parameters immediately. I could fix this by by not set those 2 static parameters in setDefaultParameters() but given a static value.

**Comment by greenbreakfast** [comment]
@vsemi since the [`FrameBuilder` constructor](https://github.com/OnionIoT/tau-lidar-common/blob/master/TauLidarCommon/d3.py#L194) sets the range and color mode, it should be safe to remove the `setColorMode` and `setRange` calls from `Camera.setDefaultParameters()`.

Please try that out and let me know how it goes? 
If everything works fine, commit the changes and we'll make a new release

**Comment by greenbreakfast** [comment]
@vsemi thanks!
