### ISSUE TITLE
recording frames frame size error

### ISSUE THREAD

**Issue by kevinboards** [OnionIoT/tau-lidar-camera#12]
This issue refers to this conversation
https://community.onion.io/topic/4509/tau-usb-cable-suggestions

### Python Library versions

Python 3.9.5
pip 21.1.1

### Camera Info
ToF Camera opened successfully
model: 4.0
firmware: 3.3
uid: 9500c6
resolution: 160x60
port: COM8

### Describe the bug
example recordRawFrames.py  runs slow and has lots of bad frames.  
The shell acquires a frame at sporadic intervals.    I have recorded 2 clips of the frame recording and play back.   The first video shows whats happening in the shell, then I flipped the orientation of the USB-C cable as a test and ran a second video.  Same results.   

### Steps to Reproduce
step 1 - Use USB A to USB C cable - 3" long, 
step 2 - run replayRawFrames.py from shell

### What is expected?
frames to be captured at regular intervals
folder filling up with good frames, bad frames not kept

### What is actually happening?
frames are captured at irregular intervals,  between 0.5 seconds and 25 seconds

frames are typically bad.   error: 'Data error, actual size: 38356, expected size: 38480

replayRawFrame.py error message 'Bad frame ignored, bytes length 38276' 

*** notice the size error on recording and the size error on replay are different sizes.  This is the same for every rejected file.

### Any additional comments?
I will add 2 frames, one good and one bad.   
1625280643.067339.frame - good frame
1625280658.6192925.frame - bad frame
I will add the two screen recordings

Here is the Zip folder 
 https://drive.google.com/file/d/1ugfV21nifUp86CioeHIdQ1R-xqKZseBW/view?usp=sharing

**Comment by greenbreakfast** [comment]
@kevinboards To confirm, this only happens with the `recordRawFrames.py` example program, and the rest of the example programs work as expected?

The same questions from #13 will be helpful here as well:
* Does this happen every time you try to run `recordRawFrames.py` ?
* Has it worked as expected before? If so, did it consistently work as expected or only from time to time?
* Do you have multiple Tau Cameras, and if so, does this happen with all of them?

**Comment by kevinboards** [comment]
> @kevinboards To confirm, this only happens with the `recordRawFrames.py` example program, and the rest of the example programs work as expected?
Correct, recordRawFrames.py acts this way but the other example programs function fine 
 
> The same questions from #13 will be helpful here as well:
 
> * Does this happen every time you try to run `recordRawFrames.py` ?
Yes
> * Has it worked as expected before? If so, did it consistently work as expected or only from time to time?
No, never as expected. 
> * Do you have multiple Tau Cameras, and if so, does this happen with all of them?
I only have 1 camera

**Comment by kevinboards** [comment]
UPDATE: Today I was able to get my hands on an old windows 7 machine.   I downloaded Python 3.7, setup everything for the TauLidarServer and it ran  really well!  No problems.  
I then downloaded the examples, the recording of frames was incredibly fast and all of my frames were good frames.    

The Tau Camera is obviously fine.  There is something going on with my lenovo laptop with python 3.9 that I will need to get to the bottom of.

**Comment by greenbreakfast** [comment]
@kevinboards my guess is the serial port on your lenovo is the culprit here and for #13 

Could you look into the details of the COM ports for both machines and see if you can find any differences?

It looks like there's also a fix on the way that might help with this - see issue #14

**Comment by greenbreakfast** [comment]
@kevinboards Looks like this issue and #13 is a combo of two problems:

* A bug causing the `bad frame ignored` error (#14)
* A USB issue with Thinkpad laptops (#16)

A fix for the `bad frame ignored` error has been fixed and released in TauLidarCamera v0.0.4. You can update by running `python -m pip install TauLidarCamera --upgrade`. (Just make sure v0.0.4 is installed).
And the USB issue can be resolved by updating your Thinkpad's BIOS. 

Please try that out and let us know how it goes.

**Comment by kevinboards** [comment]
@greenbreakfast   
Updated TauLidarCamera package with the exact instructions you gave above.   
Did not make any changes to BIOS (it should be up to date but I didn't do anything here) 

Camera now works as expected, this bad frame bug was the cause for me.   

I can now Record frames properly and use TauLidarServer properly. 

Thanks for all the hard work team!  You should be able to close this issue and issue #13

**Comment by greenbreakfast** [comment]
@kevinboards awesome, happy to hear everything is working properly now! 
Gonna close this issue and #13 

It would be much appreciated if you could also post a brief update on the Onion Community that TauLidarCamera v0.0.4 fixes the issue - better visibility for other users who may experience the same thing.
