### ISSUE TITLE
Invalid data error

### ISSUE THREAD

**Issue by vsemi** [OnionIoT/tau-lidar-camera#14]
Issue found on a windows machine, sometimes serial port lost a few bytes, cause invalid data error.

**Comment by vsemi** [comment]
@greenbreakfast should I check in this fix into trunk?

**Comment by vsemi** [comment]
@greenbreakfast also I may suggest you guys to have a test on Mac (I tested Windows and Linux).

**Comment by greenbreakfast** [comment]
@vsemi please make a new branch for the fix and we'll try it out on a Mac

**Comment by vsemi** [comment]
@greenbreakfast Looks like #14 is related to #13 and #12, I found the issue (#14) on my new ThinkPad with python 3.9, so please confirm if works for (#13 and #12).

**Comment by vsemi** [comment]
@greenbreakfast it is still slow on my new ThinkPad with python 3.9, but the error fixed. the reason of why ThinkPad with python 3.9 is slow, still unknown.

**Comment by vsemi** [comment]
@greenbreakfast updated BIOS solved the "slow" issue (lower frame rate compared to older ThinkPad) for my new ThinkPad. The fix of issue 14 is still necessary just in case (make sure no bytes lost when whatever the serial port happens).

**Comment by greenbreakfast** [comment]
@vsemi glad to hear you found a solution for the lower frame rate. What prompted you to try updating the BIOS? 
(I'll be adding this to our troubleshooting guide and it would be nice to provide some context)

**Comment by vsemi** [comment]
@greenbreakfast Googled complaint about Lenovo USB serial issue, and Lenovo has a trouble shooting page indicated updating BIOS:  https://support.lenovo.com/ca/en/solutions/ht080247-troubleshooting-usb-devices-thinkpad, guessed if it was related to the issue we had, and my new ThinkPad was just prompting for updating BIOS, I accepted the update and the problem gone. New test concludes: the fix still needed to prevent the data error and getting every frame successful, even with BIOS update. In other words, to properly fix the issue on newer ThinkPad, need the fix in branch issue_14 plus BIOS update.

**Comment by greenbreakfast** [comment]
@vsemi thanks! 

Fix released in [TauLidarCamera v0.0.4](https://github.com/OnionIoT/tau-lidar-camera/releases/tag/v0.0.4)

Updated [troubleshooting guide](https://github.com/OnionIoT/tau-lidar-server/blob/master/GET-STARTED.md#bad-frame-ignored-error---update-your-tau-camera-software-and-try-out-a-better-cable) to suggest updating Tau Camera software when encountering `bad frame ignored` error - commit 68c48fd45b8228330df2bd3f27cd07b22d3cccb3



---

Splitting the slow frame rate problem into its own issue for better tracking. See #16
