### ISSUE TITLE
Auto detect available device

### ISSUE THREAD

**Issue by mh1412** [OnionIoT/tau-lidar-camera#2]
# User Story 
- User plugs in Tau ToF Camera in to the computer
- User calls `Camera.open(auto=True)` without specifying device name
- Library returns the first valid Tau Camera device

# Background
Currently Camera.open() takes the first available Serial port without checking if it is a valid Tau Camera device. By reading the device version info the driver can tell if the device is valid or not.

**Comment by greenbreakfast** [comment]
closing this issue for now, will re-open if any issues are discovered with further testing
