### ISSUE TITLE
i want to know if i can get the real distance in every pixel in the depth image

### ISSUE THREAD

**Issue by praymich** [OnionIoT/tau-lidar-camera#23]
### Python Library versions
python：3.10.0

### Camera Info
    model:      4.0
    firmware:   3.3
    uid:        60003C
    resolution: 160x60
    port:       COM3

### Describe the bug

![Uploading 1.jpg…]()

### What is expected?
i want to know if i can get the real distance in every pixel in the depth image

**Comment by greenbreakfast** [comment]
@praymich your image failed to upload so I don't have the full context. 

But it is 100% possible to get the distance measurement of each pixel. Start by looking at the example python programs, specifically `distance.py`: https://github.com/OnionIoT/tau-lidar-camera/tree/master/examples

And then follow the API documentation to see how to extract depth data from the frames: https://taulidarcamera.readthedocs.io/

Let us know how it goes!

**Comment by praymich** [comment]
> @praymich your image failed to upload so I don't have the full context.
> 
> But it is 100% possible to get the distance measurement of each pixel. Start by looking at the example python programs, specifically `distance.py`: https://github.com/OnionIoT/tau-lidar-camera/tree/master/examples
> 
> And then follow the API documentation to see how to extract depth data from the frames: https://taulidarcamera.readthedocs.io/
> 
> Let us know how it goes!

oh thank you，i get it . i also want know the meaning in the data_depth, the scale unit is meter? like examle,
<class 'array.array'> 1.0356920957565308 means distance 1.03m about?

**Comment by greenbreakfast** [comment]
@praymich yep, the scale is meters. You can confirm this visually using the camera - perhaps holding your hand about 50cm away and confirming the program outputs about 0.5m.

I'm going to go ahead and close this issue. If you have any further questions, feel free to open a new issue or join the conversation on the [Onion Community Forum](https://community.onion.io/)
