### ISSUE TITLE
Add quickstart documentation

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-camera#5]
Added a skeleton for a quickstart documentation article. Please add in the content.

For an example of a good quickstart page see https://requests.readthedocs.io/en/latest/user/quickstart/

**Comment by vsemi** [comment]
Added some text and how to get other types of frames, how it looks? also by the way I'm not able to format the things nicely, although struggled for a long, for example the github instruction how to format code block, but it did not work for me.

**Comment by greenbreakfast** [comment]
@vsemi looks good! I think this is fine for now, we'll see what questions our users raise

I did some research + fiddled around with the text and got the code blocks to work

For reference, a code block looks like this:

```
.. code-block:: python

   cameraInfo = camera.info()

   print("\nToF camera opened successfully:")
   print("    model:      %s" % cameraInfo.model)
   print("    firmware:   %s" % cameraInfo.firmware)
   print("    uid:        %s" % cameraInfo.uid)
   print("    resolution: %s" % cameraInfo.resolution)
   print("    port:       %s" % cameraInfo.port)
```

It's very finicky actually, won't work if there's no blank line after the `.. code-block:: python` line

You can also use the [local build instructions](https://github.com/OnionIoT/tau-lidar-camera/blob/master/docs/README.md) and debug using the command-line output from the `make html` command.

**Comment by vsemi** [comment]
@greenbreakfast great, I corrected a few typo and added "Next step" at the bottom.
