### ISSUE TITLE
Review API reference

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-camera#6]
Try following the instructions in [docs/README.md](https://github.com/OnionIoT/tau-lidar-camera/blob/master/docs/README.md) to build the docs

Review the API reference and see if there's a better way to present the information.

Source code for the api reference document can be found here: https://github.com/OnionIoT/tau-lidar-camera/blob/master/docs/api.rst
It's written in [reStructuredText](https://devguide.python.org/documenting/)

See also https://github.com/OnionIoT/tau-lidar-common/issues/1

**Comment by vsemi** [comment]
@greenbreakfast reviewed and modified comments for autodoc, generated locally and looks good now.
