### ISSUE TITLE
Example program with amplitude doesn't run properly

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-camera#8]
### Python Library versions
> Run `pip list | grep TauLidar` in the command-line and paste the output

TauLidarCamera 0.0.1
TauLidarCommon 0.0.1
opencv-python  4.4.0.46
numpy          1.19.4

Running on a Mac

### Camera Info
> If possible, paste the output of `camera.info()` from Python (after camera has been successfully opened)

```
ToF camera opened successfully:
    model:      4.0
    firmware:   3.3
    uid:        69.549
    resolution: 160x60
    port:       /dev/cu.usbmodem00000000001A1
```

### Describe the bug
Running the `distancePlusAmplitude.py` example program, results in a bunch of bad frame errors and now windows showing frames from the camera.

### Steps to Reproduce

1. Create new python virtual environment and activate it
1. Install TauLidarCamera python module using pip
1. Install opencv-python module using pip
1. Run `python examples/distancePlusAmplitude.py`

### What is expected?

Two windows to appear, one with depth map and the other with amplitude coming in real time from the camera

### What is actually happening?

No windows open, command line prints following errors:

```
Data error, actual size: 35644, expected size: 38480
Bad frame ignored, bytes length: 35564
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
Bad frame ignored, bytes length: 0
```

Continues on like this

### Any additional comments?

The `distancePlusGrayscale.py` example program works as expected:

![Screen Shot 2020-11-27 at 3 42 56 PM](https://user-images.githubusercontent.com/6757320/100483532-4b9ae680-30c7-11eb-8fd2-366071c73cc1.png)

**Comment by vsemi** [comment]
![depth-amplitude](https://user-images.githubusercontent.com/57770238/100657530-48e4ff00-331c-11eb-8539-150b1c6f8ab4.png)
@greenbreakfast Tested and worked well on Windows. 
![depth-amplitude-console](https://user-images.githubusercontent.com/57770238/100658077-7df15180-331c-11eb-946c-765534be0716.png)

**Comment by greenbreakfast** [comment]
Tried again but using an apple usb-c to usb-c cable and it worked with no issue. I've added a troubleshooting section and documented this error and resolution. Both here and in https://github.com/OnionIoT/tau-lidar-server/

Closing this issue since we have a resolution
