### ISSUE TITLE
Color range mismatch between point cloud and depth map

### ISSUE THREAD

**Issue by greenbreakfast** [OnionIoT/tau-lidar-camera#9]
### Python Library versions
> Run `pip list | grep TauLidar` in the command-line and paste the output. Include some details on your system as well

```
TauLidarCamera            0.0.1
TauLidarCommon            0.0.1
TauLidarServer            0.0.2
```

Running on Mac

### Camera Info
> If possible, paste the output of `camera.info()` from Python (after camera has been successfully opened)

```
ToF camera opened successfully:
    model:      4.0
    firmware:   3.3
    uid:        69.549
    resolution: 160x60
    port:       /dev/cu.usbmodem00000000001A1
    IP address: 127.0.0.1
    URL:  http://127.0.0.1:8081
```

### Describe the bug

The color representing depth is different between the point cloud and depth map. They should follow the same coloring for consistency

### Steps to Reproduce

1. Start the TauLidarServer program
1. Navigate to the point cloud viewer in the web app
1. Change the setting of the "Color Range" slider
1. Observe difference in coloring of point cloud and depth map
1. Repeat two previous steps

### What is expected?

Consistent colors to represent depth in both the depth map and point cloud

### What is actually happening?

<img width="1552" alt="Screen Shot 2020-11-27 at 4 48 27 PM" src="https://user-images.githubusercontent.com/6757320/100486629-ab4abf00-30d2-11eb-9bcd-2298c1c7c825.png">
<img width="1552" alt="Screen Shot 2020-11-27 at 4 48 21 PM" src="https://user-images.githubusercontent.com/6757320/100486634-b00f7300-30d2-11eb-870b-130ae5b4bcde.png">
<img width="1552" alt="Screen Shot 2020-11-27 at 4 48 07 PM" src="https://user-images.githubusercontent.com/6757320/100486636-b0a80980-30d2-11eb-92bd-6f4d33624f18.png">
<img width="1552" alt="Screen Shot 2020-11-27 at 4 47 59 PM" src="https://user-images.githubusercontent.com/6757320/100486639-b140a000-30d2-11eb-99f7-7eb03fd0ce4a.png">
<img width="1552" alt="Screen Shot 2020-11-27 at 4 47 52 PM" src="https://user-images.githubusercontent.com/6757320/100486640-b30a6380-30d2-11eb-8ab5-dd4635577f85.png">

**Comment by vsemi** [comment]
@greenbreakfast The issue was in server, fixed.
